---@diagnostic disable: missing-fields
vim.pack.add(require("load").gh({ "mrjones2014/smart-splits.nvim" }))
require("smart-splits").setup({})

vim.keymap.set("n", "<A-h>", function()
    require("smart-splits").resize_left()
end, { nnoremap = true, desc = "smart-splits - resize left" })
vim.keymap.set("n", "<A-j>", function()
    require("smart-splits").resize_down()
end, { nnoremap = true, desc = "smart-splits - resize down" })
vim.keymap.set("n", "<A-k>", function()
    require("smart-splits").resize_up()
end, { nnoremap = true, desc = "smart-splits - resize up" })
vim.keymap.set("n", "<A-l>", function()
    require("smart-splits").resize_right()
end, { nnoremap = true, desc = "smart-splits - resize right" })
vim.keymap.set("n", "<C-h>", function()
    require("smart-splits").move_cursor_left()
end, { nnoremap = true, desc = "smart-splits - move cursor left" })
vim.keymap.set("n", "<C-j>", function()
    require("smart-splits").move_cursor_down()
end, { nnoremap = true, desc = "smart-splits - move cursor down" })
vim.keymap.set("n", "<C-k>", function()
    require("smart-splits").move_cursor_up()
end, { nnoremap = true, desc = "smart-splits - move cursor up" })
vim.keymap.set("n", "<C-l>", function()
    require("smart-splits").move_cursor_right()
end, { nnoremap = true, desc = "smart-splits - move cursor right" })
vim.keymap.set("n", "<leader>bh", function()
    require("smart-splits").swap_buf_left()
end, { nnoremap = true, desc = "smart-splits - swap buffer left" })
vim.keymap.set("n", "<leader>bj", function()
    require("smart-splits").swap_buf_down()
end, { nnoremap = true, desc = "smart-splits - swap buffer down" })
vim.keymap.set("n", "<leader>bk", function()
    require("smart-splits").swap_buf_up()
end, { nnoremap = true, desc = "smart-splits - swap buffer up" })
vim.keymap.set("n", "<leader>bl", function()
    require("smart-splits").swap_buf_right()
end, { nnoremap = true, desc = "smart-splits - swap buffer right" })
